// This file is auto-generated by scripts/generate-i18n-locale.ts
// DONT EDIT THIS FILE MANUALLY
import common_ardz from "@locales/common/ar-DZ.json"
import common_ariq from "@locales/common/ar-IQ.json"
import common_arkw from "@locales/common/ar-KW.json"
import common_arma from "@locales/common/ar-MA.json"
import common_arsa from "@locales/common/ar-SA.json"
import common_artn from "@locales/common/ar-TN.json"
import common_de from "@locales/common/de.json"
import common_en from "@locales/common/en.json"
import common_es from "@locales/common/es.json"
import common_fi from "@locales/common/fi.json"
import common_fr from "@locales/common/fr.json"
import common_it from "@locales/common/it.json"
import common_ja from "@locales/common/ja.json"
import common_ko from "@locales/common/ko.json"
import common_pt from "@locales/common/pt.json"
import common_ru from "@locales/common/ru.json"
import common_tr from "@locales/common/tr.json"
import common_zhCN from "@locales/common/zh-CN.json"
import common_zhHK from "@locales/common/zh-HK.json"
import common_zhTW from "@locales/common/zh-TW.json"
import external_en from "@locales/external/en.json"

import type { ns, SSRSupportedLanguages } from "./constants"

/**
 * This file is the language resource that is loaded in full when the app is initialized.
 * When switching languages, the app will automatically download the required language resources,
 * we will not load all the language resources to minimize the first screen loading time of the app.
 * Generally, we only load english resources synchronously by default.
 * In addition, we attach common resources for other languages, and the size of the common resources must be controlled.
 */
export const defaultResources = {
  en: {
    common: common_en,
    external: external_en,
  },
  "zh-CN": {
    common: common_zhCN,
  },
  "zh-HK": {
    common: common_zhHK,
  },
  ja: {
    common: common_ja,
  },
  ru: { common: common_ru },
  fi: { common: common_fi },
  it: { common: common_it },
  "ar-DZ": { common: common_ardz },
  "ar-SA": { common: common_arsa },
  "ar-MA": { common: common_arma },
  "zh-TW": { common: common_zhTW },
  es: { common: common_es },
  fr: { common: common_fr },
  pt: { common: common_pt },
  "ar-IQ": { common: common_ariq },
  "ar-KW": { common: common_arkw },
  "ar-TN": { common: common_artn },
  de: { common: common_de },
  ko: { common: common_ko },
  tr: { common: common_tr },
} satisfies Record<
  SSRSupportedLanguages,
  Partial<Record<(typeof ns)[number], Record<string, string>>>
>
