export const COMMAND_ID = {
  entry: {
    read: "entry:read",
    readAbove: "entry:read-above",
    readBelow: "entry:read-below",
    viewSourceContent: "entry:view-source-content",
    readability: "entry:ability",
    openInBrowser: "entry:open-in-browser",
    star: "entry:star",
    toggleAISummary: "entry:toggle-ai-summary",
    toggleAITranslation: "entry:toggle-ai-translation",
    imageGallery: "entry:image-gallery",
    copyLink: "entry:copy-link",
    copyTitle: "entry:copy-title",
    tts: "entry:tts",
    exportAsPDF: "entry:export-as-pdf",
    tip: "entry:tip",
    delete: "entry:delete",
    share: "entry:share",
  },
  integration: {
    saveToEagle: "integration:save-to-eagle",
    saveToReadwise: "integration:save-to-readwise",
    saveToInstapaper: "integration:save-to-instapaper",
    saveToObsidian: "integration:save-to-obsidian",
    saveToOutline: "integration:save-to-outline",
    saveToReadeck: "integration:save-to-readeck",
    saveToCubox: "integration:save-to-cubox",
  },
  list: {
    edit: "list:edit",
    unfollow: "list:unfollow",
    navigateTo: "list:navigate-to",
    openInBrowser: "list:open-in-browser",
    copyUrl: "list:copy-url",
    copyId: "list:copy-id",
  },
  settings: {
    changeThemeToAuto: "follow:change-color-mode-to-auto",
    changeThemeToDark: "follow:change-color-mode-to-dark",
    changeThemeToLight: "follow:change-color-mode-to-light",
    customizeToolbar: "follow:customize-toolbar",
  },
  global: {
    showShortcuts: "global:show-shortcuts",
  },
  layout: {
    toggleTimelineColumn: "layout:toggle-timeline-column",
  },
  timeline: {
    switchToNext: "timeline:switch-to-next",
    switchToPrevious: "timeline:switch-to-previous",
    refetch: "timeline:refetch",
  },
  entryRender: {
    scrollDown: "entry-render:scroll-down",
    scrollUp: "entry-render:scroll-up",
  },
} as const
