export const RSSHubCategories = [
  "all",
  "social-media",
  "new-media",
  "traditional-media",
  "bbs",
  "blog",
  "programming",
  "design",
  "live",
  "multimedia",
  "picture",
  "anime",
  "program-update",
  "university",
  "forecast",
  "travel",
  "shopping",
  "game",
  "reading",
  "government",
  "study",
  "journal",
  "finance",
] as const

export const CategoryEmojiMap: Record<(typeof RSSHubCategories)[number], string> = {
  all: "🌟",
  "social-media": "💬",
  "new-media": "📱",
  "traditional-media": "📰",
  bbs: "👥",
  blog: "✍️",
  programming: "👨‍💻",
  design: "🎨",
  live: "🎥",
  multimedia: "🎬",
  picture: "📸",
  anime: "🌸",
  "program-update": "🔄",
  university: "🎓",
  forecast: "🔮",
  travel: "✈️",
  shopping: "🛍️",
  game: "🎮",
  reading: "📚",
  government: "🏛️",
  study: "📝",
  journal: "📔",
  finance: "💹",
} as const
